### ISSUE TITLE
dependency on axios cause break in at least 04_typeahead

### ISSUE THREAD

**Issue by pkellner** [dai-shi/react-hooks-async#1]
Nice work! Learning a lot here.  Seems that there is a breaking dependency on axios and node-fetch someplace causing at least the 04_typeahead app to error with "npm start". I also noticed the same error from a codepen app but don't remember where.

**Comment by dai-shi** [comment]
Oh, my. Thanks for reporting! Will take care.

**Comment by pkellner** [comment]
Glad you are up. Maybe this is the world's way of telling me I need to go out for a bike ride and if I'm lucky, maybe when I'm back it will be fixed.  I love your code design and architecture. I'm just learning TypeScript (not much of node wizard) and I'm confident I can learn a lot from your work.  Thank you so much for sharing.

**Comment by dai-shi** [comment]
Fixed!
