### ISSUE TITLE
How to prevent an initial run

### ISSUE THREAD

**Issue by ed-sparkes** [dai-shi/react-hooks-async#12]
Hi, 

Really like what you have done here, but have a query if that is ok ?

I want to run an async axios delete when the user clicks a button on a row of data. When the page loads i dont want to run the delete as the user has not selected the row yet. On my button click i am setting state to update the row to delete and the async delete function is run and the row deleted. How can i prevent it from running on initial load? 

I tried following the example using start function so on my button click set state and call start but the function is run before the state update has taken affect and so the row info is still missing. 

Not sure if the above makes sense. Let me know if you need more info. 

Thanks, Ed

**Comment by dai-shi** [comment]
So, you are using `start()` function. That sounds OK.
Can you share code snippet or preferably small codesandbox for reproduction?

**Comment by ed-sparkes** [comment]
Will try and put together a codesandbox today. What i think i am after is away to not run a task when a dependency is unset. For example i have a combined task one that gets an access token and then a second one that calls api endpoint via axios. despite the fact i am using useAsyncCombineSeq the second one runs with no access token, is cancelled when the first one completes with access token and then runs again correctly. How do i avoid that inital run? 

Is there anyway to put a condition on the task run if dependency not undefined?

**Comment by dai-shi** [comment]
Currently, `deps` is simply fed into `useEffect`, so you cannot stop a task by setting it to `undefined`.
With `useAsyncCombineSeq`, the second one is supposed to wait until the first one is resolved.
Look forward to your codesandbox.

**Comment by ed-sparkes** [comment]
OK 

Please see a contrived example on codesandbox

https://codesandbox.io/s/unruffled-robinson-8hnxw

You can see there are two async tasks, the first calls an api to get a fake access token and then the second should be called when the first completes. 

I have deferred running the combined task until a button click. 

When i run this and click the button , the first task is run but the second is never run.

Thanks, Ed

**Comment by ed-sparkes** [comment]
Ok, so i worked out why the start doesnt really work. The start is run on click but after state change component re-renders and is then stoppped again, also realised that i have been fiddling with the codesandbox so no longer does what i said it did previously oops, so probably not worth looking at that 

Reading about a bit including https://github.com/facebook/create-react-app/issues/6917#issuecomment-486972155 
It seems that the conditionally fetch or run an async function the condition needs to be inside useEffect. 

Something like this seems to work ....


```
import { useEffect } from "react";

export const useAsyncRunConditionally = (asyncTask, startCondition) => {
  console.log("start" + startCondition());
  const start = startCondition() ? asyncTask && asyncTask.start : undefined;
  const abort = asyncTask && asyncTask.abort;
  useEffect(() => {
    if (start) {
      start();
    }
  }, [start, startCondition]);
  useEffect(() => {
    const cleanup = () => {
      if (abort) {
        abort();
      }
    };
    return cleanup;
  }, [abort]);
};

export default useAsyncRunConditionally;

```

Can you see any issues with this, and if not would you entertain a PR to your library to support this?

**Comment by dai-shi** [comment]
I see your problem. Thanks for sharing your example.

Now, `useAsyncRun` is provided for conditional execution, so you wouldn't need a new one.

The real problem is that `useAsyncCombineSeq` is not designed for chaining results.
In your case, access token can be used commonly for all requests, I would define as a separate task.

I've updated your example. https://codesandbox.io/s/amazing-shirley-pmc0b

Not sure if it solves your all use cases. Please feel free to share new examples if any.

**Comment by ed-sparkes** [comment]
Brilliant, thanks, this answers my questions for now

**Comment by digitaltopo** [comment]
I'm trying to do the same using the `useAsyncTaskFetch` helper. Adding the following code in my component causes the component to infinitely render, seems like the deps for this helper aren't wired up properly?

```
...
const deleteTask = useAsyncTaskFetch(
    'https://jsonplaceholder.typicode.com/posts/1',
    {
      method: 'DELETE',
    }
  );
...
```
Minimal Reproducible Example:
https://codesandbox.io/s/wonderful-cache-cjp0t?fontsize=14

What am I missing? Thanks for your help!

**Comment by digitaltopo** [comment]
I rewrote the helper inside my own code to actually ask for deps instead of using the original arguments. Seems to work for me so far, something like:

```
const defaultInit = {};
const defaultReadBody = body => body.json();

const createFetchError = message => {
  const err = new Error(message);
  err.name = 'FetchError';
  return err;
};

const useAsyncTaskFetch = (
  {url: input, config = defaultInit, readBody = defaultReadBody},
  deps = []
) =>
  useAsyncTask(async abortController => {
    const response = await fetch(input, {
      signal: abortController.signal,
      ...config,
    });
    if (!response.ok) {
      throw createFetchError(response.statusText);
    }
    const body = await readBody(response);
    return body;
  }, deps);

export default useAsyncTaskFetch;
```
instead of https://github.com/dai-shi/react-hooks-async/blob/master/src/use-async-task-fetch.js

What I did makes sense I think, but would still like to understand if I'm missing something when I was trying to get it to work out of the box. If the helper just has an oversight, happy to make a PR.

**Comment by dai-shi** [comment]
Please try defining the option outside of hooks, if they are independent.

```javascript
const fetchOption = {
  method: 'DELETE',
};

const deleteTask = useAsyncTaskFetch(
  'https://jsonplaceholder.typicode.com/posts/1',
  fetchOption,
);
```

**Comment by dai-shi** [comment]
About the helper, I'm currently rewriting the entire API to avoid `deps`. This will be a breaking change.
This change is because of recent trend in React. The more idiomatic way seems to useMemo/useCallback at the caller end.

I will file a PR and ask a feedback from you.

**Comment by digitaltopo** [comment]
Thank you for the update @dai-shi
