### ISSUE TITLE
importing from src

### ISSUE THREAD

**Issue by ed-sparkes** [dai-shi/react-hooks-async#13]
Hi, 

Apologies as i am sure this a simple question but ... 

When i import from src e.g.

`import useAsyncTaskAxios from 'react-hooks-async/src/use-async-task-axios'`

this works fine in my code but not in my tests 

i get ` SyntaxError: Unexpected identifier`

guessing its because the ES6 modules not compiling but not sure how to modify my jest config to sort it out. If i import from `dist` then the type information is not available? 

jest.config.js 

```javascript
module.exports = {
    "roots": [
      "<rootDir>/src"
    ],
    "transform": {
      "^.+\\.tsx?$": "ts-jest"
    },
    "moduleDirectories": ["node_modules", "src"],
    "testRegex": "(/__tests__/.*|(\\.|/)(test|spec))\\.tsx?$",
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "jsx",
      "json",
      "node"
    ],
    "reporters": [ "default", "jest-junit" ]
  }
```

Any thoughts welcome thanks, Ed

**Comment by dai-shi** [comment]
Could you try to import from `dist` instead of `src`? `*.d.ts` is also there.

----
Now, I think importing from sub dirs is only confusing, and it's bad idea.
I want to fix it. Only the reason why it is so is to avoid axios dependency.
I have an idea, but it's a breaking change. I'll do it anyway...

**Comment by ed-sparkes** [comment]
importing from dist i get a warning saying 

`Could not find declaration file for module ...`

Yeah importing from src folder does seem a bit odd 

happy with a breaking change :)

**Comment by dai-shi** [comment]
> happy with a breaking change :)

😁 I will work on it.

**Comment by dai-shi** [comment]
> *.d.ts is also there.

this was my misunderstanding.

**Comment by dai-shi** [comment]
Published `3.0.0-alpha.0`. Please give it a try.

**Comment by ed-sparkes** [comment]
brilliant, all working for me, unit tests now run :) and code still works, just inject axios as a dependency

**Comment by dai-shi** [comment]
Cool. Good to hear that.

I'm thinking of adding another breaking change in the API for v3. Please be patient.

**Comment by ed-sparkes** [comment]
No worries, breaking changes are good, would you mind giving me some basic advice on how to mock this for my tests, could i just mock the axios functions that it uses or should i mock the whole thing?

**Comment by dai-shi** [comment]
Although I haven't tried, I would mock the entire hook for unit tests and mock axios for integration test like with react-testing-library. To be honest, I'm not an expert on tests.

**Comment by dai-shi** [comment]
v3 is already published, so let me close this issue.
