### ISSUE TITLE
infinite re-rendering when calling useAsyncTaskFetch hook

### ISSUE THREAD

**Issue by dagda1** [dai-shi/react-hooks-async#16]
I am calling `useAsyncTaskFetch` from one of my own hooks:

```javascript
export const useApi = <TResponse>(
  url: string,
  options: UseApiOptions<TResponse> = { httpMethod: HTTPMethod.GET },
): UseApiResult<TResponse> => {
  // TODO: needed to add useMemo  with empty deps to stop
  // infinite re-rendering
  // eslint-disable-next-line
  const config = useMemo(() => createConfig(options), []);

  const asyncTask = useAsyncTaskFetch<TResponse>(url, config);
  useAsyncRun(asyncTask);
```

This is causing a re-render because the options object being a new object each time if I do not use `useMemo` or something.

Is this expected behaviour?

**Comment by dai-shi** [comment]
Yes. The current version requires callers to memoize parameters.
What would be better is to let the caller of `useApi` memoize `options`.

I think it's idiomatic in React now (which might be changed in the future, though).
It was a long way for me to reach here too. Please see [my related comment](https://github.com/dai-shi/react-hooks-async/pull/15#issuecomment-508768651).

It's better to enable exhaustive-deps rule. In your case, I would do something like this:
```javascript
const config = useMemo(() => createConfig(options.httpMethod, options.something), [options.httpMethod, options.something]);
```

**Comment by dai-shi** [comment]
Closing this. Feel free to reopen if there're still any questions.
