### ISSUE TITLE
useFetch: Infinite re-rendering only when NODE_ENV=production

### ISSUE THREAD

**Issue by supermihi** [dai-shi/react-hooks-async#19]
I am experiencing an infinite re-rendering (leading to infinite re-fetch) with the `useFetch` hook, but only when building in production mode (`NODE_ENV=production`), not in development-build or running with webpack dev-server.

Honestly I have no clues on how to further debug the issue. The hook depends on a static string only:
```jsx
export default ({ selection, setSelection }: Props) => {
  const { result: availableData, ...props } = useFetch<AvailableDataMap>(dataFilesUrl);
  const nodes = useSelector(selectNodes);

  if (props.error) return <Alert color="error">{`Error fetching data: ${props.error}`}</Alert>;
  if (props.pending) return <Spinner type="grow" />;

  if (!selection || selection.length === 0) {
    setSelection(Object.keys(availableData).map(nodeId => ({ nodeId, filename: availableData[nodeId][0] })));
  }
  /* ... */
```

**Comment by dai-shi** [comment]
Oh no, that's unexpected. It could be a bug.
Did you try with a smaller example? like the one in the `examples` folder?

**Comment by dai-shi** [comment]
I built `examples/02_typescript` and it worked without any problems.

@supermihi Could you make a small reproduction of the issue please?

**Comment by supermihi** [comment]
Sure, I'll try to build a reproducible example asap.

**Comment by supermihi** [comment]
Sorry for the delay. I removed anything specific to my project and the problem still persists. See [this repository](https://github.com/supermihi/debug-react-hooks-async).

To reproduce:
- `yarn install`
- `yarn run build:prod`
- serve `./dist` with any HTTP server, e.g. `python -m http.server --directory dist`

When opening the page in the browser, you will see `loading...` all the time. In browser dev tools, you can seet hat network requests are continuously.

**Comment by dai-shi** [comment]
Thanks! I will take a look at it after my vacation.

**Comment by supermihi** [comment]
Just noticed that adding
```json
optimization: {
    minimizer: []
  }
```
to `webpack.config.js` lets the problem disappear ... so it's probably a bug in the minimizer?

**Comment by dai-shi** [comment]
That’s good to know!

I haven’t tried your example yet, but that means we can reproduce the issue with the examples in the repo, doesn’t it?

**Comment by supermihi** [comment]
I wasn't able to reproduce it with those examples ... perhaps `react-scripts` is using a different minimizer configuration under the hood?

**Comment by dai-shi** [comment]
I understand the issue. terser minifies too much. `defaultReadBody` is inlined.

Among [compress options](https://github.com/terser/terser#compress-options), `reduce_vars` seems to do this. So, the following works:

```js
  optimization: {
    minimizer: [
      new TerserPlugin({
        terserOptions: {
          compress: {
            reduce_vars: false,
          },
        },
      }),
    ],
  },
```

**Comment by dai-shi** [comment]
Maybe related: https://github.com/terser/terser/issues/350

**Comment by dai-shi** [comment]
Published https://www.npmjs.com/package/react-hooks-async/v/3.4.0 with the workaround in  665cc67.

**Comment by supermihi** [comment]
Perfect, thanks for the quick fix!
