### ISSUE TITLE
Still can not get 04_typeahead example to work, same error

### ISSUE THREAD

**Issue by pkellner** [dai-shi/react-hooks-async#2]
Here are the steps
fresh clone of repo master branch
cd examples/04_typeahead
npm i
npm start

Get error
Type error: Cannot find module 'node-fetch'.  TS2307

  > 1 | import { Body, Request, RequestInit } from 'node-fetch';

**Comment by pkellner** [comment]
BTW, my node version is 11.4.0, npm is 6.5.0 and I'm running windows 10.

**Comment by pkellner** [comment]
I did notice that before I could add axios and it would work. I did a little research on peer dependency errors and it sounds like an ugly issue.  Thanks for looking into it.

**Comment by dai-shi** [comment]
I ended up adding @types/node-fetch in examples. I may remove the dependency from the library in the future.
