### ISSUE TITLE
3.1.0 breaks conditional running with useAsyncRun

### ISSUE THREAD

**Issue by dgreuel** [dai-shi/react-hooks-async#20]
The documentation for useAsyncRun says 

> This can be a falsy value and in that case it won't run any tasks. Hence, it's possible to control the timing by:
> `useAsyncRun(ready && task);
> `

But v.3.1.0 removes the falsy check from useAsyncRun (line 4), so I get an error: **TypeError: Cannot read property 'start' of null**. Is there a different way to do this now?

**Comment by dai-shi** [comment]
Oh noooooo! That's my mistake. Thanks tons! Will fix in a moment.

**Comment by dai-shi** [comment]
Published: https://www.npmjs.com/package/react-hooks-async/v/3.1.1

Thanks again. Please feel free to report issues if you find any.

**Comment by dgreuel** [comment]
Thank you! Appreciate the quick response.
