### ISSUE TITLE
Issue with tests and .start() since 3.2.0

### ISSUE THREAD

**Issue by ed-sparkes** [dai-shi/react-hooks-async#23]
Apologies i tried to create code sandbox to recreate, but apparently doesnt support jest.mock which my test is using. 

So thought i would raise and see if you could think of anything obvious. 

Two of my unit tests started failing after upgrading to 3.2.0, both relate to async actions that are invoked by calling the start() function on button click, both are supposed to start axios tasks which i have mocked. The text on the button should change when the action completes, and this is working fine in the code but the unit test is suddenly failing. I am using react testing library to wait on the button state change, but the  task.result never seems to resolve

Any thoughts greatly welcome.

Here is a simple example of the code https://codesandbox.io/s/wizardly-hooks-425yz
as you can see the button state does change, unfortunately i cant reproduce the failing test due to codesandbox not supporting jest.mock but you can see the test code at least. 

Thanks, Ed

**Comment by dai-shi** [comment]
Hmm, no, I don't see anything obvious from the code.
It it specifically since 3.2.0? In other words, does it work with 3.1.1?
Can it reproduce the error, if I download the codesandbox?

**Comment by ed-sparkes** [comment]
Apologies for wasting your time, have now worked out the issue, was an issue with the test, i must of made another change at the same time, facepalm moment
