### ISSUE TITLE
useAsyncTaskFetch doesn't provide access the response body if server returns error

### ISSUE THREAD

**Issue by denisborovikov** [dai-shi/react-hooks-async#24]
Hi there, thank you for the great library!

I've found that `useAsyncTaskFetch` doesn't allow to get access to the server response body if an error occurred.

[Here](https://github.com/dai-shi/react-hooks-async/blob/master/src/use-async-task-fetch.js#L30) it returns only `statusText`, but in some cases, it can be not enough.

In my particular case, the server responds with 500 error and the body:
```
{
  "errorId": "a70eb1e0-0d11-4d6c-8ace-d3043f7e5bfc",
  "errorCode": 10215,
  "errorMessage": "Campaign item with such name already exists",
  "params": "{}"
}
```

But hook's `error` contains only - `FetchError: Server error`.

Thanks again for the work you do!

**Comment by dai-shi** [comment]
Good catch!

Should we add the body in the error object?
```js
const createFetchError = (message, responseBody) => {
  const err = new Error(message);
  err.name = 'FetchError';
  err.responseBody = responseBody;
  return err;
};
```
What would you suggest?

**Comment by denisborovikov** [comment]
Yes, that's what I was about to suggest. Thanks for the fastest reply ever!

**Comment by dai-shi** [comment]
@denisborovikov 
Could you try 4d137af and see if it works for your use case?

**Comment by denisborovikov** [comment]
It works perfectly 👍

**Comment by dai-shi** [comment]
Published!
https://www.npmjs.com/package/react-hooks-async/v/3.4.2

Thanks for your contribution.

**Comment by denisborovikov** [comment]
Thank you!
