### ISSUE TITLE
what is the purpose of the started flag

### ISSUE THREAD

**Issue by dagda1** [dai-shi/react-hooks-async#26]
I was having a quick play around in [this codesandbox](https://codesandbox.io/s/ds-coding-assignment-yojex).

I was following the examples which follow this pattern:

```javascript
  if (!started) {
    return (
      <div>
        <button onClick={() => start()}>GET</button>
      </div>
    );
  }

  // code will never get here because started will be false by the time result has resolved

  if (error) return <Err error={error} />;
  if (pending) return <Loading abort={abort} />;

  if (!result) {
    return <div>No Beers today!</div>;
  }

  // display results
```

The problem is that in my example anyway.

By the time I have a `result`, `started` will be false.  

I have to change the first if statement to this:

`if (!started && !result) {`

I wonder if rather than individual `error`, `loading`, `pending` states, there should actually be a state machine where you are only ever in one state rather than individual flags.

Or am I misunderstanding how started workds.

**Comment by dai-shi** [comment]
You would probably only need `pending`. `started` is required for `useAsyncCombine*`. We could think about removing it from the public API.

I thought about the combined state, but I thought the current `pending`, `error` and `result` is somewhat intuitive enough.
For reference, see TS types:
https://github.com/dai-shi/react-hooks-async/blob/af0241b32d697b3c3e4d29ed0e82f4cf797a6e37/src/index.d.ts#L6-L20

**Comment by dagda1** [comment]
you could have these as:

```
 { 
   pending: boolean; 
   error: Error | null; 
   result: Result | null; 
 } 
```

**Comment by dai-shi** [comment]
No, it's not the same. That's the point. If pending is false, either error or result is non-null.
```
if (pending) return 'Loading';
if (error) return 'Error';
// otherwise we are sure that the result is `Result` type
```
