### ISSUE TITLE
Return a promise from task.start()

### ISSUE THREAD

**Issue by denisborovikov** [dai-shi/react-hooks-async#27]
What do you think if `task.start()` function would return a promise which could be fulfilled with task's results or rejected in case of error?

In some scenarios, it's more preferable rather than tracking task's pending/result values,
i.e. `const { pending, error, result } = task;`

**Comment by dai-shi** [comment]
Thanks for you suggestion. I think it's generally a good idea.
The implementation might be a bit tricky.
Do you think it's ok to update task values *and* return a promise?
That means even if you receive a result from a promise, the component will re-render.

**Comment by denisborovikov** [comment]
In my opinion, it's completely ok. Now I'm worrying more about the API rather than additional re-renders.

I think apollo's [hooks](https://www.apollographql.com/docs/react/api/react-hooks/) (useMutation as example) use similar approach. They update values and return a promise as well.

**Comment by dai-shi** [comment]
@denisborovikov wanna review #28?

**Comment by denisborovikov** [comment]
@dai-shi Thank you for the quick reply and fast update! I very much appreciate your work.

**Comment by dai-shi** [comment]
Published: https://www.npmjs.com/package/react-hooks-async/v/3.5.0
