### ISSUE TITLE
How to handle FetchError?

### ISSUE THREAD

**Issue by Alxblsk** [dai-shi/react-hooks-async#36]
He there, 

Thank you for creating these hooks, they are really useful for me.

One thing I noticed is when a request returns 404, an additional message propagates to console:

```
Uncaught (in promise) FetchError: Not Found
    at createFetchError
```

Is there a way to efficiently handle FetchError and avoid error message propagation in console?

**Comment by dai-shi** [comment]
Hi, thanks for reporting.
Throwing an error is intentional in useAsyncTask start(), but we can catch and ignore it in useAsyncRun, because we are likely to handle it with the state returned by useAsyncTask.

I can fix this and see if it works.

**Comment by dai-shi** [comment]
You can try with this commit:
```bash
npm install 'github:dai-shi/react-hooks-async#d998166'
```

Please let me know if this helps in your use case.

**Comment by Alxblsk** [comment]
@dai-shi yes, thanks, it fixed an error throwing for `useAsyncRun`. However, looks like this is still a case for `useFetch`.

**Comment by dai-shi** [comment]
@Alxblsk `useFetch` internally uses `useAsyncRun`. Do you still see an error in console with `useFetch`?

**Comment by Alxblsk** [comment]
@dai-shi I double checked the use case. I don't see an error any more if I pass a task inside of `useAsyncRun`, but I still get one of two errors if I use `useAsyncCombineAll` inside, like:

```
useAsyncRun(useAsyncCombineAll(task1, task2));
```

**Comment by dai-shi** [comment]
@Alxblsk Oh, I got it. Thanks for the investigation!

**Comment by dai-shi** [comment]
Please try the latest commit 59273d1.

**Comment by Alxblsk** [comment]
@dai-shi seems working now. Thanks!

**Comment by dai-shi** [comment]
Published: https://www.npmjs.com/package/react-hooks-async/v/3.9.0

Thanks for your contribution.
