### ISSUE TITLE
Error without statusText via HTTP/2 protocol

### ISSUE THREAD

**Issue by Avantjurist** [dai-shi/react-hooks-async#40]
Hi

I use useFetch hook via HTTP/2 protocol. I need to handle Error via statusCode or statusText. According to the spec:
> HTTP/2 does not define a way to carry the version or reason phrase that is included in an

It means i don't have methods for getting statusCode or statusText.
It is good idea to add statusCode to the error. What do you think?

Thanks

**Comment by dai-shi** [comment]
Thanks for reporting. Actually, I got exactly the same concern in a discussion in Twitter.
Let's fix it. Adding statusCode is OK. Or do we have a better solution? What do you think about attaching the response object as a whole?

**Comment by Avantjurist** [comment]
Any variant suits me, but fist will be better. As for me adding response object as a whole isn't needed because when we handle error, we use only statusCode from error
Thanks

**Comment by dai-shi** [comment]
@Avantjurist Would you review #41?

**Comment by dai-shi** [comment]
Let me release it and see how it works out.

**Comment by dai-shi** [comment]
Published: https://www.npmjs.com/package/react-hooks-async/v/3.10.0

**Comment by Avantjurist** [comment]
Could you please  my comment in closed PR

**Comment by dai-shi** [comment]
https://www.npmjs.com/package/react-hooks-async/v/3.10.1
Fixed. Thanks for your review!
