### ISSUE TITLE
Unhandled promise rejection error

### ISSUE THREAD

**Issue by gsavvid** [dai-shi/react-hooks-async#47]
I'm not sure how errors are supposed to be handled. I have the following function that returns a promise:

```
  getFacebookToken(): Promise<string> {
    return LoginManager.logInWithPermissions(['public_profile'])
      .then((response) => {
        if (response.isCancelled) {
          // This error is not handled.
          throw Error('Request canceled');
        } else {
          return AccessToken.getCurrentAccessToken();
        }
      })
      .then((response) => response.accessToken)
  }
```

When I use the above with `useAsyncTask` and if the promise throws an error, then this is not handled and, also, the `task.error` is always `null`. 

Thank you in advance.

PS. I'm using this in React Native, not ReactJS.

**Comment by dai-shi** [comment]
Hi, thanks for trying!
Throwing an error is intentional, because otherwise we would not be able to know it in other hooks like useAsyncCombine.
If you use useAsyncRun, the error is caught. #36 
So, I assume you call `task.start` on your end in callbacks?
Could you wrap the call with try-catch?

> also, the task.error is always null.

This is unexpected. I may misunderstand something of your use case. Let me know if the problem persists.

**Comment by gsavvid** [comment]
Hi @dai-shi, 

Thank you very much for the quick response. Apparently, I was mistaken about `task.error`. I don't know how I missed that but the error is updated properly if the promise throws an error. Sorry about the confusion there.

Yes, I call `task.start`. My understanding was that `useAsyncRun()` is used when you want to run the task immediately, while `task.start` when you need to start it in a callback. 

I could add a `catch` at the end of my promise if that's what you mean but then the question is how will the component get notified that the promise was rejected? Perhaps I'm missing something obvious here.

Here's the entire code:

```
const fetchLoginWithFacebook = (_abortController: AbortController) => {
  return LoginManager.logInWithPermissions(['public_profile'])
    .then((response) => {
      if (response.isCancelled) {
        throw Error('Request canceled');
      } else {
        return AccessToken.getCurrentAccessToken();
      }
    })
    .then((response) => response.accessToken)
};

export default function SignInPage(props: SignInPageProps) {
  const {start: startLoginWithFacebookTask, result: facebookLogin, started: facebookLoginLoading, error: facebookError} = useAsyncTask(fetchLoginWithFacebook);

  const onFacebookLoginPress = useCallback(() => {
    startLoginWithFacebookTask();
  }, [startLoginWithFacebookTask]);

  return (
    <LoadingSignInView
      isLoading={facebookLoginLoading}
      title={Strings.signInTitle}
      subtitle={Strings.signInSubtitle}
      bottomButtonPrompt={Strings.signUpPrompt}
      bottomButtonText={Strings.signUp}
      onFacebookButtonPress={onFacebookLoginPress}
    />
  );
}
```

**Comment by dai-shi** [comment]
Thanks for the clarification.

> I could add a `catch` at the end of my promise if that's what you mean but then the question is how will the component get notified that the promise was rejected? Perhaps I'm missing something obvious here.

Your understanding is correct. So, we shouldn't add `catch` there.

What I mean is something like this:

```jsx
export default function SignInPage(props: SignInPageProps) {
  const {start, result: facebookLogin, started: facebookLoginLoading, error: facebookError} = useAsyncTask(fetchLoginWithFacebook);
  const startLoginWithFacebookTask = useCallback(async () => {
    try {
      await start();
    } catch (e) {
      // ignore
    }
  }, [start]);

  return (
    <LoadingSignInView
      isLoading={facebookLoginLoading}
      title={Strings.signInTitle}
      subtitle={Strings.signInSubtitle}
      bottomButtonPrompt={Strings.signUpPrompt}
      bottomButtonText={Strings.signUp}
      onFacebookButtonPress={startLoginWithFacebookTask}
    />
  );
}
```

It looks annoying to do this every time.
As the philosophy of react-hooks-async is composability, we create a new hook instead of modifying useAsyncTask.

```js
const useAsyncTaskIgnoringError = (func) => {
  const task = useAsyncTask(func);
  return useMemo(() => ({
    ...task,
    start: async (...args) => {
      try {
        await task.start(...args);
      } catch (e) {
        // we ignore this error because it's handled with state
      }
    },
  }), [task]);
};
```

Hope it helps.

**Comment by gsavvid** [comment]
Thank you very much, that's a great solution. 

Here's the Typescript equivalent of your solution in case someone else stumbles upon this:

```
const useAsyncTaskIgnoringError = <Result, Args extends unknown[]>(func: (c: AbortController, ...args: Args) => Promise<Result>): AsyncTask<Result, Args> => {
  const task = useAsyncTask(func);
  return useMemo(() => ({
      ...task,
      start: async (...args: Args) => {
        try {
          return await task.start(...args);
        } catch (e) {
          // We ignore this error because it's handled with the state.
          console.log('Error: ' + e);
        }
      },
    }), [task]);
};
```

**Comment by gsavvid** [comment]
A slight modification that doesn't use an anonymous function because the previous one might cause an infinite loop if `start` is used inside a hook such as `useEffect`:

```
export const useAsyncTaskIgnoringError = <Result, Args extends unknown[]>(func: (c: AbortController, ...args: Args) => Promise<Result>): AsyncTask<Result, Args> => {
  const task = useAsyncTask(func);
  const {start} = task;

  const startWithIgnoringError = useCallback(
    async (...args: Args) => {
      try {
        return await start(...args);
      } catch (e) {
        // We ignore this error because it's handled with the state.
        console.log('Error: ' + e);
      }
    },
    [start]
  );

  return useMemo(
    () => ({
      ...task,
      start: startWithIgnoringError,
    }),
    [task, startWithIgnoringError]
  );
};
```

**Comment by dai-shi** [comment]
Ah, nice catch!
