### ISSUE TITLE
why not use only typescript ?

### ISSUE THREAD

**Issue by sibelius** [dai-shi/react-hooks-async#5]
in this way you don't need to generate all .d.ts

**Comment by dai-shi** [comment]
Yeah, that's a bit ugly. It used to be only one index.d.ts and a bunch of *.js.
Later, I needed to split files for bundlers that do not support tree shaking.

To answer to your question, while I enjoy coding in TypeScript,
I like coding in JavaScript. I also assume some people only read or like JavaScript.

I don't mind moving to TypeScript if the majority of contributors to this project prefer so.

**Comment by dai-shi** [comment]
Closing this for now. Feel free to reopen for discussion.

(I might re-design the src/dist structure. It's not very nice to import a file deep in directories.)
