### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by alexstanbury** [dai-shi/react-hooks-async#7]
I create a new project using latest create-react-app then install this lib. 
I then paste in the useFetch demo code from the README.
When compiling I get the following error:

```
./node_modules/react-hooks-async/dist/use-async-task-fetch.js
Module not found: Can't resolve 'core-js/modules/es6.array.filter' in '/Users/mynamehere/Desktop/myprojectname/node_modules/react-hooks-async/dist'
```

It's strange because that module is definitely in that location inside node_modules. Any ideas? Thanks

**Comment by dai-shi** [comment]
Hi, thanks for reporting.
Could you try replacing `dist` in the import lines to `src` please?

**Comment by alexstanbury** [comment]
Thanks for the quick reply!

Setting to `src` fixes it and now works as expected.

**Comment by dai-shi** [comment]
Good. I'll think about how I can resolve this...

**Comment by dai-shi** [comment]
https://www.npmjs.com/package/react-hooks-async/v/2.1.0 fixed!

(it was simply core-js version mismatch...)
